name: Clojure CI

on:
  push:
    branches: [ '*' ]
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - uses: graalvm/setup-graalvm@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        version: 'latest'
        java-version: '21'
        components: 'native-image'
        distribution: 'graalvm-community'
        native-image-musl: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build native image
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      run: |
        lein native-image
        mv target/parti-time ./parti-time-linux-x86_64
        sha512sum ./parti-time-linux-x86_64 > ./parti-time-linux-x86_64.sha512
    - uses: actions/upload-artifact@v4
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        name: parti-time-linux-x86_64
        path: parti-time-linux-x86_64*
